version: 2
jobs:
  build_test:
    working_directory: ~/circleci-wknml
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      - run:
          name: Install tools
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: Python tests
          command: |
            mkdir -p testoutput
            pytest tests/

workflows:
  version: 2
  default:
    jobs:
      - build_test