version: 2
jobs:
  build_test:
    working_directory: ~/circleci-wknml
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: Python tests
          command: tests/scripts/python_tests.sh

workflows:
  version: 2
  default:
    jobs:
      - build_test